from __future__ import annotations

from pocketlab.schemas import ExplorationSource, ExplorationTemplate, SensorKind

PHYPOX_SENSORS = "https://phyphox.org/sensors/"
PHYPOX_REMOTE_API = (
    "https://phyphox.org/wiki/index.php?title=Remote-interface_communication"
)
PHYPOX_EXPERIMENTS = "https://github.com/phyphox/phyphox-experiments"

_COMMON_SOURCES = [
    ExplorationSource(
        label="phyphox 官方传感器列表",
        url=PHYPOX_SENSORS,
        role="确认手机传感器类型、单位与设备差异。",
    ),
    ExplorationSource(
        label="phyphox 官方实验集合",
        url=PHYPOX_EXPERIMENTS,
        role="对应实验配置与可复现实验设计的参考入口。",
    ),
]


def _template(
    exploration_id: str,
    title: str,
    question: str,
    category: str,
    primary_sensor: SensorKind,
    readiness: str,
    action_kind: str,
    readiness_note: str,
    duration_minutes: int,
    difficulty: str,
    protocol: list[str],
    expected_signal: str,
    output_value: str,
    *,
    safety_notes: list[str] | None = None,
    privacy_notes: list[str] | None = None,
    secondary_sensors: list[SensorKind] | None = None,
    executable_protocol_id: str | None = None,
    simulation_question: str | None = None,
    simulation_scope_note: str | None = None,
) -> ExplorationTemplate:
    return ExplorationTemplate(
        exploration_id=exploration_id,
        title=title,
        question=question,
        category=category,
        primary_sensor=primary_sensor,
        secondary_sensors=secondary_sensors or [],
        readiness=readiness,
        readiness_note=readiness_note,
        action_kind=action_kind,
        executable_protocol_id=executable_protocol_id,
        simulation_question=simulation_question,
        simulation_scope_note=simulation_scope_note,
        duration_minutes=duration_minutes,
        difficulty=difficulty,
        protocol=protocol,
        expected_signal=expected_signal,
        output_value=output_value,
        safety_notes=safety_notes or [],
        privacy_notes=privacy_notes or [],
        sources=_COMMON_SOURCES,
    )


EXPLORATION_CATALOG = [
    _template(
        "vibration-source-triage",
        "生活设备的振动从哪里来？",
        "异常振动更像偏载、松动、传振，还是结构放大？",
        "设备与居住环境",
        "accelerometer",
        "analysis_ready",
        "bounded_agent",
        "旧版真机诊断链仍保留；新增 NIST 真实 Android 响应回放和受限 Agent Beta，设备故障因果与 Gate C/E 仍需用户真机对照。",
        20,
        "入门",
        ["固定手机并记录原始工况。", "一次只改变一个候选原因。", "用同测点复测并比较 RMS 与主频。"],
        "有效干预会使 RMS、频谱峰值或谐波结构沿关键预测变化。",
        "一份证据绑定的原因判断、处理建议和可选复测标准。",
        safety_notes=["出现漏电、漏水、焦糊味或剧烈位移时立即停止。"],
        privacy_notes=["公开 NIST 数据只允许本机回放，不会冒充你的 phyphox 真机记录。"],
        executable_protocol_id="vibration-response-public-exploration.v1",
        simulation_question="公开静止与手持加速度记录能否区分运动响应？",
        simulation_scope_note="公开回放只验证静止—运动测量链，不诊断具体生活设备的偏载、松动或故障原因。",
    ),
    _template(
        "walking-cadence-map",
        "我的步频在不同路面会变吗？",
        "三段公开楼梯上行的步频候选是否稳定，下一步怎样设计不同路面的真机对照？",
        "人体运动",
        "accelerometer",
        "analysis_ready",
        "bounded_agent",
        "NIST 真实 Android 楼梯回放、步频/SNR/重复性门和受限 Agent Beta 已接通；不同路面因果及 Gate C/E 仍待用户真机重复。",
        15,
        "入门",
        ["把手机固定在同一口袋或腰包。", "每种路面稳定行走 20 秒。", "保持路线安全并重复一次。"],
        "步频峰值通常可重复，路面和步态会改变冲击幅值与谐波。",
        "不同场景的步频、RMS 与重复性比较。",
        safety_notes=["只在平整、安全、无车辆的路线测量；不要边看手机边走。"],
        privacy_notes=["公开 NIST 数据只允许本机回放；不会写入账号或用于医疗判断。"],
        executable_protocol_id="walking-cadence-public-exploration.v1",
        simulation_question="三段公开楼梯上行记录的步频候选是否稳定？",
        simulation_scope_note="公开回放只验证楼梯记录中的步频重复性，不比较草地、瓷砖等真实路面因果。",
    ),
    _template(
        "elevator-motion-profile",
        "电梯什么时候加速、匀速和减速？",
        "一段电梯行程的竖直加速度能否还原运动阶段？",
        "运动与交通",
        "accelerometer",
        "analysis_ready",
        "bounded_agent",
        "NIST 真实 Android 电梯回放、正加速—稳定—减速阶段门和受限 Agent Beta 已接通；位移/楼层积分被禁止，Gate C/E 仍待用户真机重复。",
        10,
        "入门",
        ["手机保持静止并确认竖直方向。", "从电梯静止前开始记录到到站后。", "重复同一楼层区间。"],
        "启动和制动阶段出现相反方向的加速度变化，中间阶段更接近稳定。",
        "行程事件时间线与重复行程的相似性。",
        safety_notes=["不要妨碍电梯门或在拥挤环境中布置手机。"],
        privacy_notes=["公开 NIST 数据只允许本机回放，不会冒充你的电梯真机记录。"],
        executable_protocol_id="elevator-motion-public-exploration.v1",
        simulation_question="三段公开电梯上行记录能否重复检测加速、稳定与减速阶段？",
        simulation_scope_note="公开回放验证电梯阶段顺序与重复性，不推断当前电梯的精确楼层或位移。",
    ),
    _template(
        "rotation-rate-check",
        "转盘真的匀速吗？",
        "旋转物体在一圈内的角速度是否稳定？",
        "旋转运动",
        "gyroscope",
        "analysis_ready",
        "bounded_agent",
        "NIST 真实 Android 回放、专用质量门和受限 Agent Beta 已接通；Gate C/E 仍待用户 phyphox 真机重复。",
        12,
        "入门",
        ["把手机可靠固定在低速转台中心附近。", "先静止记录，再低速转动。", "比较不同设定的角速度稳定性。"],
        "匀速阶段角速度接近平台，启动和停止阶段呈明显过渡。",
        "平均角速度、波动范围与启停时间。",
        safety_notes=["不得手持手机进行高速旋转；必须可靠固定并限制转速。"],
        privacy_notes=["公开 NIST 数据只允许本机回放，不会冒充你的 phyphox 真机记录。"],
        executable_protocol_id="gyroscope-public-exploration.v1",
        simulation_question="公开陀螺仪记录能否区分静止和手持转动？",
        simulation_scope_note="公开回放只比较静止与手持角运动，不证明转盘匀速、精确转角或绝对姿态。",
    ),
    _template(
        "magnetic-field-walk",
        "日常物体怎样改变局部磁场？",
        "扬声器、钢制家具和电源线附近的磁场变化能否被空间定位？",
        "场与空间",
        "magnetometer",
        "analysis_ready",
        "bounded_agent",
        "NIST 真实 Android 回放、uT/accuracy 专用质量门和受限 Agent Beta 已接通；物体因果、空间地图及 Gate C/E 仍待用户 phyphox 真机重复。",
        20,
        "进阶",
        ["先在远离金属的位置记录背景。", "保持手机方向不变，按固定间距移动。", "记录距离并重复往返扫描。"],
        "局部磁性或通电物体附近的场强会偏离背景，方向改变也会影响各轴读数。",
        "相对背景的磁场剖面和异常位置。",
        safety_notes=["不靠近高压设备、强磁体或医疗植入物限制区域。"],
        privacy_notes=["公开 NIST 数据只允许本机回放，不会冒充你的 phyphox 真机记录。"],
        executable_protocol_id="magnetometer-public-exploration.v1",
        simulation_question="公开磁力计记录能否区分稳定背景和局部场变化？",
        simulation_scope_note="公开回放只验证稳定—变化状态分离，不识别具体物体，也不生成真实空间磁场地图。",
    ),
    _template(
        "light-distance-law",
        "灯光随距离怎样衰减？",
        "点状光源的照度是否近似随距离平方反比下降？",
        "光与环境",
        "light",
        "analysis_ready",
        "bounded_agent",
        "单条 lx 分析器保持 analysis_ready；距离协议已进入受限 Agent Beta，Gate C/E 仍待成组真机与完整循环。",
        15,
        "入门",
        ["关闭自动变化的其他光源。", "保持传感器正对灯，在多个已知距离记录。", "每个位置等待读数稳定。"],
        "理想点光源在远场近似平方反比；环境光、光源尺寸和入射角会造成偏离。",
        "距离—相对照度曲线与模型偏差。",
        safety_notes=["不要对太阳、激光或高温强光源近距离测量。"],
        executable_protocol_id="light-distance-law.v1",
        simulation_question="遮挡和触摸条件下的两条公开光照序列有什么数值差异？",
        simulation_scope_note="公开回放演示光照条件对照，不包含已知距离，不能验证原实验的平方反比定律。",
    ),
    _template(
        "pressure-elevator-altitude",
        "气压能看见楼层变化吗？",
        "同一栋楼上下移动时，手机气压计能否稳定分辨高度变化？",
        "大气与高度",
        "pressure",
        "analysis_ready",
        "bounded_agent",
        "公开 NIST Pressure 回放、隐藏真值质量门和受限 Agent Beta 已接通；Gate C/E 仍待用户 phyphox 真机重复。",
        15,
        "入门",
        ["在起点静置记录背景气压。", "乘电梯到目标楼层并再次静置。", "返回起点检查漂移。"],
        "上升时气压通常下降；返回起点应接近原值，但天气与室内压差会引入漂移。",
        "相对气压差、估计高度差和回程误差。",
        safety_notes=["遵守场所规则，不进入受限区域。"],
        privacy_notes=["公开 NIST 数据只允许本机回放；不会写入账号，也不会冒充你的真机记录。"],
        executable_protocol_id="pressure-public-exploration.v1",
        simulation_question="公开手机气压数据能否看见电梯上升的相对高度变化？",
        simulation_scope_note="公开回放验证相对气压与隐藏高程的一致性，不代表当前手机、当前楼层或绝对海拔。",
    ),
    _template(
        "room-acoustic-response",
        "房间哪些位置让声音更响？",
        "同一声源下，房间位置是否形成可重复的相对强弱分布？",
        "声音与空间",
        "microphone",
        "analysis_ready",
        "bounded_agent",
        "真实 NoiseCapture 派生级别回放、隐私最小化、时间窗口质量门和受限 Agent Beta 已接通；房间位置因果、Gate C/E 仍待用户 phyphox 真机重复。",
        20,
        "进阶",
        ["固定声源、音量和测试片段。", "在网格位置使用同一手机方向记录。", "重复一个位置检查漂移。"],
        "驻波和反射可能形成位置相关的相对峰谷，但手机自动增益会影响幅值。",
        "相对声学热区与重复性，不输出合规分贝结论。",
        safety_notes=["使用舒适音量并缩短暴露；不测试极高声压。"],
        privacy_notes=["避免录入对话；只保存派生特征，不保留原始音频。公开 NoiseCapture 回放仅在本机运行。"],
        executable_protocol_id="microphone-public-exploration.v1",
        simulation_question="公开声音派生级别序列的前后变化范围是否明显？",
        simulation_scope_note="公开回放只比较派生相对级别，不包含原始音频，也不能证明当前房间的声场分布。",
    ),
    _template(
        "gps-route-consistency",
        "同一路线的速度记录有多稳定？",
        "重复走同一路线时，GPS 速度与轨迹误差在开阔和遮挡环境下有何差异？",
        "位置与城市环境",
        "location",
        "analysis_ready",
        "bounded_agent",
        "真实 Android Go!Track 公开回放、隐私投影、重复路线质量门和受限 Agent Beta 已接通；accuracy/status、开阔—遮挡因果及 Gate C/E 仍待用户 phyphox 真机重复。",
        25,
        "进阶",
        ["选择安全公开路线并记录开阔段与遮挡段。", "以相近速度重复两次。", "比较速度和轨迹偏移。"],
        "建筑遮挡通常增加位置跳变，开阔区域的重复轨迹更一致。",
        "速度曲线、轨迹一致性与遮挡影响。",
        safety_notes=["不要边走边操作手机，不进入车道或危险区域。"],
        privacy_notes=["公开回放已移除绝对坐标、绝对时间与设备标识，但相对路线形状仍可能被地图匹配；仅允许确认后的本机运行。"],
        executable_protocol_id="location-public-exploration.v1",
        simulation_question="两次公开相似路线的长度和相对形状有多一致？",
        simulation_scope_note="公开回放只比较隐私变换后的相对路线，不验证开阔—遮挡因果或当前手机定位误差。",
    ),
    _template(
        "proximity-response",
        "距离传感器看到的是连续距离还是开关？",
        "不同材质和角度下，手机接近传感器的触发距离是否一致？",
        "传感器行为",
        "proximity",
        "analysis_ready",
        "bounded_agent",
        "NIST 真实 Android 稀疏事件回放、二态状态门和受限 Agent Beta 已接通；材质、角度、触发距离及 Gate C/E 仍待用户 phyphox 真机重复。",
        10,
        "入门",
        ["确定传感器大致位置。", "用非尖锐物体从多个距离缓慢接近。", "改变材质或角度并重复。"],
        "许多手机只报告近/远两态，触发距离会受结构、材质和厂商实现影响。",
        "触发模式、近似距离与重复性。",
        safety_notes=["不要用尖锐物接触屏幕或传感器开孔。"],
        privacy_notes=["公开 NIST 数据只允许本机回放，不会冒充你的 phyphox 真机记录。"],
        executable_protocol_id="proximity-public-exploration.v1",
        simulation_question="公开接近传感器事件的前后片段是否呈现稳定二态？",
        simulation_scope_note="公开回放只验证近—远二态事件，不包含受控材质、角度或实际触发距离。",
    ),
    _template(
        "external-sensor-extension",
        "手机之外还能接入什么？",
        "能否用 BLE 外部传感器把温度、力或自制装置接入 PocketLab？",
        "开放式测量",
        "bluetooth",
        "planned",
        "capability_check",
        "phyphox 支持 Bluetooth 输入/输出，但 PocketLab 尚未实现设备配对、通道 schema 和回放门禁。",
        30,
        "进阶",
        ["先在 phyphox 中验证 BLE 实验能稳定读数。", "记录设备、单位和采样率。", "再定义 PocketLab 通道映射。"],
        "外部设备应输出带单位、时间戳和可重复零点的通道。",
        "可扩展的外部传感器数据集与实验模板。",
        safety_notes=["自制电路使用安全低压供电，并遵守传感器额定范围。"],
        privacy_notes=["配对标识和设备地址不应进入公开数据集。"],
    ),
]


def list_explorations() -> list[ExplorationTemplate]:
    return [item.model_copy(deep=True) for item in EXPLORATION_CATALOG]


def exploration_ids_for_sensors(sensors: list[SensorKind]) -> list[str]:
    available = set(sensors)
    return [
        item.exploration_id
        for item in EXPLORATION_CATALOG
        if item.primary_sensor in available
    ]
